# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "aarch64/openjdk:11"
  amd64: "amd64/openjdk:11"
  armhf: "armhf/openjdk:11"
  armv7: "arm32v7/openjdk:11"
  i386: "i386/openjdk:11"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Smart Appliance Enabler"
  org.opencontainers.image.description: "The Smart Appliance Enabler is a software for integrating any device (Wallbox, heat pump, washing machine, dishwasher, ...) with the Sunny Home Manager by SMA"
  org.opencontainers.image.source: "https://github.com/MoellerDi/hassio-addons"
  org.opencontainers.image.licenses: "GNU GENERAL PUBLIC LICENSE"
args:
  BASHIO_VERSION: 0.14.3
  TEMPIO_VERSION: 2021.09.0
