# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Smart Appliance Enabler test
version: "1.0.0"
slug: addon-smartapplianceenabler-test
description: Smart Appliance Enabler is software for integrating any device (Wallbox, heat pump, washing machine, dishwasher, ...) with Sunny Home Manager by SMA
url: "https://github.com/MoellerDi/hassio-addons/SmartApplianceEnabler"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: false
ingress_port: 8080
ingress_entry: status
ports: {}
ports_description: {}
host_network: true
map:
  - share:rw
  - config:rw
options:
  sae_www_port: "8080"
schema:
  sae_www_port: "int"
services:
  - mqtt:need
#image: "ghcr.io/moellerdi/{arch}-addon-smartapplianceenabler"
